/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailySummary {
  'totalCaloriesBurned' : bigint,
  'totalSteps' : bigint,
  'totalCaloriesConsumed' : bigint,
  'netCalories' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FoodEntry {
  'date' : string,
  'calories' : bigint,
  'image' : ExternalBlob,
  'foodName' : string,
}
export interface StepRecord { 'date' : string, 'steps' : bigint }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFoodEntry' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    undefined
  >,
  'getAllStepRecords' : ActorMethod<[], Array<StepRecord>>,
  'getAvailableDates' : ActorMethod<[], Array<string>>,
  'getDailySummary' : ActorMethod<[string], DailySummary>,
  'getEntriesForDate' : ActorMethod<[string], Array<FoodEntry>>,
  'getEntriesForDateSortedByFood' : ActorMethod<[string], Array<FoodEntry>>,
  'getSteps' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];